name: Pipelineworkflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
   build:
       name: Azure Pipeline
       runs-on: ubuntu_latest
       steps:
       - name: Azure Pipeline Action
         uses: Azure/pipeline@v1
         with:
           azure-devops-project-url: https://dev.azure.com/ayanghosh07/AgileProject
           azure-devops-pipeline-name: 'webapp'
           azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}